### ISSUE TITLE
What about a non-beta release?

### ISSUE THREAD

**Issue by melroy89** [alessiobianchini/ng-flex-layout#8]
# Proposal

#### What is the summary of the proposal?

We could just create a release and remove "beta", right? I think we are good to go.

This also make this fork looks more "stable", if you don't have a beta release anymore as latest official release. In the future you can still have alpha & beta releases, however be sure to mark those releases as "Pre-release" under GitHub.

**Comment by alessiobianchini** [comment]
Hi @melroy89, 
We agree with you, in the latest version all the automated tests have been restored and we can remove the beta now.

We can also leave the beta version to not definitive versions.

Thanks for your suggestion! :)
